OnlineWeb/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineWeb.Data;
using OnlineWeb.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.IO;
using OnlineWeb.Models.ViewModels;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using System.ComponentModel;
using Microsoft.AspNetCore.Identity;

namespace OnlineWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        public CartController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // Helper method to get the cart from session


        // Helper method to save the cart to session

        // Action method to show the cart
        public async Task<IActionResult> ViewCart()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" }); // Redirect to login if user is not logged in
            }
            // Directly use the method to get cart from session
            var cartViewModel = new CartViewModel();

            var CartItems = await _context.CartItems.ToListAsync();

            foreach (var item in CartItems)
            {
                var itemViewModel = new CartItemViewModel
                {
                    ProductId = item.ProductId,
                    ProductName = item.ProductName,
                    ProductImageUrl = item.ProductImageUrl,
                    Quantity = item.Quantity,
                    Price = item.Price
                };
                cartViewModel.Items.Add(itemViewModel);
            }

            var cartId = 1; // Example cart ID, replace with actual logic to identify the cart
            var cart = await _context.Carts.FirstOrDefaultAsync(c => c.CartId == cartId);

            if (cart != null)
            {
                ViewBag.TotalQuantity = cart.TotalQuantity; // Pass the total quantity to the view
            }
            else
            {
                ViewBag.TotalQuantity = 0; // Default to 0 if no cart is found
            }


            return View(cartViewModel);
        }

        public async Task<IActionResult> AddToCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" }); // Redirect to login if user is not logged in
            }
            var cartId = 1;

            var cart = await _context.Carts.FirstOrDefaultAsync(c => c.CartId == cartId);
            if (cart == null)
            {
                // Create a new Cart since it doesn't exist
                cart = new Cart { CartId = cartId };
                _context.Carts.Add(cart);
                await _context.SaveChangesAsync(); // Ensure the cart is saved and exists in the database
            }



            var product = await _context.Products
                .Include(p => p.ProductImageFiles) // Assuming you want to include related images
                .FirstOrDefaultAsync(p => p.Id == productId);

            if (product == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItems
                                         .Where(c => c.ProductId == productId && c.CartId == cartId)
                                         .FirstOrDefaultAsync();

            if (cartItem != null)
            {
                // Item already exists in the cart, increase quantity
                cartItem.Quantity++;
            }
            else
            {
                // Add new item to the cart
                cartItem = new CartItem
                {
                    CartId = cartId,
                    ProductId = product.Id,
                    ProductName = product.ProductName,
                    ProductImageUrl = product.ProductImageFiles.FirstOrDefault()?.ImageUrl ?? "default-image-url", // Example transformation
                    Price = product.Price,
                    Quantity = 1,
                };
                _context.CartItems.Add(cartItem); // Save the updated cart back to session
                Console.WriteLine("Log message: product id." + cartItem.ProductId);
            }

            await _context.SaveChangesAsync();
            var cartItems = await _context.CartItems.Where(c => c.CartId == cartId).ToListAsync();
            int TotalQuantity = cartItems.Sum(item => item.Quantity);
            float TotalPrice = cartItems.Sum(item => item.Quantity * item.Price);

            Console.WriteLine("Log message: total quatity " + TotalQuantity);
            Console.WriteLine("Log message: total price " + TotalPrice);
            cart.TotalQuantity = TotalQuantity;
            cart.AllTotalPrice = TotalPrice;

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewCart");
        }

        public async Task<IActionResult> MainAddToCart(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" }); // Redirect to login if user is not logged in
            }
            var cartId = 1;

            var cart = await _context.Carts.FirstOrDefaultAsync(c => c.CartId == cartId);
            if (cart == null)
            {
                // Create a new Cart since it doesn't exist
                cart = new Cart { CartId = cartId };
                _context.Carts.Add(cart);
                await _context.SaveChangesAsync(); // Ensure the cart is saved and exists in the database
            }

            var product = await _context.Products
                .Include(p => p.ProductImageFiles) // Assuming you want to include related images
                .FirstOrDefaultAsync(p => p.Id == productId);

            if (product == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItems
                                         .Where(c => c.ProductId == productId && c.CartId == cartId)
                                         .FirstOrDefaultAsync();

            if (cartItem != null)
            {
                // Item already exists in the cart, increase quantity
                cartItem.Quantity = quantity + cartItem.Quantity;
            }
            else
            {
                // Add new item to the cart
                cartItem = new CartItem
                {
                    CartId = cartId,
                    ProductId = product.Id,
                    ProductName = product.ProductName,
                    ProductImageUrl = product.ProductImageFiles.FirstOrDefault()?.ImageUrl ?? "default-image-url", // Example transformation
                    Price = product.Price,
                    Quantity = quantity,
                };
                _context.CartItems.Add(cartItem); // Save the updated cart back to session
                Console.WriteLine("Log message: product id." + cartItem.ProductId);
            }


            await _context.SaveChangesAsync();

            var cartItems = await _context.CartItems.Where(c => c.CartId == cartId).ToListAsync();
            int TotalQuantity = cartItems.Sum(item => item.Quantity);
            float TotalPrice = cartItems.Sum(item => item.Quantity * item.Price);

            Console.WriteLine("Log message: total quatity " + TotalQuantity);
            Console.WriteLine("Log message: total price " + TotalPrice);
            cart.TotalQuantity = TotalQuantity;
            cart.AllTotalPrice = TotalPrice;

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewCart");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateItemQuantity(int productId, int quantity)
        {
            
            var cartId = 1;
            var cart = await _context.Carts.FirstOrDefaultAsync(c => c.CartId == cartId);
            Console.WriteLine("Log message: quantity." + quantity);
            Console.WriteLine("Log message: itemid." + productId);
            if (quantity < 1)
            {
                // Handle error, e.g., by returning to the cart view with an error message
                // ModelState.AddModelError("", "Quantity must be at least 1");
                // return View("YourCartView");
                return RedirectToAction("ViewCart", new { errorMessage = "Quantity must be at least 1" });
            }

            var cartItem = await _context.CartItems.FirstOrDefaultAsync(c => c.ProductId == productId);


            if (cartItem == null)
            {
                // Handle error, e.g., by returning to the cart view with an error message
                // ModelState.AddModelError("", "Item not found");
                // return View("YourCartView");
                return RedirectToAction("ViewCart", new { errorMessage = "Item not found" });
            }

            cartItem.Quantity = quantity;
            Console.WriteLine("Log message: quantity.111" + cartItem.Quantity);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                // Log the error (uncomment ex variable name and write a log.)
                // ModelState.AddModelError("", "Unable to save changes.");

OnlineWeb/Controllers/FeedbackController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OnlineWeb.Models;
using OnlineWeb.Data;
using MailKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;

namespace OnlineWeb.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly ApplicationDbContext _context;
        public FeedbackController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Success()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public async Task<IActionResult> SendFeedback(Feedback feedback)

        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("WebApp_Feedback", "519535143@qq.com"));
            message.To.Add(new MailboxAddress("Support", "hanalau.unsw@gmail.com"));
            message.Subject = feedback.Title + "from: " + feedback.UserEmail;
            message.Body = new TextPart("html") 
            {
                Text = string.Format("<h1>{0}</h1><br><p>{1}</p>", feedback.Title, feedback.Content)
            };

            using (var client = new SmtpClient(new ProtocolLogger (Console.OpenStandardOutput ())))
            {
                client.CheckCertificateRevocation = false;

                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                client.Connect("smtp.qq.com", 587, SecureSocketOptions.StartTls);
                client.Authenticate("519535143@qq.com", "pjlvpopquwhjbjdh");
                await client.SendAsync(message);
                client.Disconnect(true);
                return RedirectToAction(nameof(Success));
            }
            return RedirectToAction("Index");
        }
    }
}

OnlineWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Amado - Furniture Ecommerce Template | Feedback</title>

    <!-- Favicon -->
    <link rel="icon" href="~/img/core-img/favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="~/css/core-style.css">
    <link rel="stylesheet" href="~/style.css">
</head>

<body>

    <!-- Mobile Nav (max width 767px)-->
    <div class="mobile-nav">
        <!-- Navbar Brand -->
        <div class="amado-navbar-brand">
            <a href="/"><img src="~/img/core-img/logo.png" alt=""></a>
        </div>
        <!-- Navbar Toggler -->
        <div class="amado-navbar-toggler">
            <span></span><span></span><span></span>
        </div>
    </div>

    <div class="container-fluid">
        <!-- Search Wrapper Area Start -->
        <div class="search-wrapper section-padding-100">
            <div class="search-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="search-content">
                            <form asp-controller="Product" asp-action="SearchProducts" method="get">
                                <input type="search" name="keyword" id="search" placeholder="Type your keyword...">
                                <button type="submit"><i class="fas fa-search" style="color: rgb(193, 188, 188);margin-right:12px;margin-left:4px;"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Search Wrapper Area End -->

        <div class="main-content-wrapper d-flex clearfix">

            <!-- Mobile Nav (max width 767px)-->
            <div class="mobile-nav">
                <!-- Navbar Brand -->
                <div class="amado-navbar-brand">
                    <a href="index.html"><img src="~/img/core-img/logo.png" alt=""></a>
                </div>
                <!-- Navbar Toggler -->
                <div class="amado-navbar-toggler">
                    <span></span><span></span><span></span>
                </div>
            </div>


            <!-- Header Area Start -->
            <header class="header-area clearfix">
                <!-- Close Icon -->
                <div class="nav-close">
                    <i class="fa fa-close" aria-hidden="true"></i>
                </div>
                <!-- Logo -->
                <div class="logo">
                    <a asp-controller="Home" asp-action="Index"><img src="~/img/core-img/logo.png" alt=""></a>
                </div>
                <!-- Amado Nav -->
                @{

                    var page = Context.Request.RouteValues.ContainsKey("action") ?
                    Context.Request.RouteValues["action"].ToString() : Context.Request.RouteValues["page"].ToString();

                }
                <nav class="amado-nav">
                    <ul>
                        <li class="@(page == "Index" ? "active" : "")"><a asp-controller="Home"
                                asp-action="Index">Home</a></li>
                        <li class="@(page == "Products" ? "active" : "")"><a asp-controller="Product"
                                asp-action="Products" asp-route-category="all" asp-route-style="all">Product</a></li>
                    </ul>
                </nav>
                <!-- Button Group -->
                <div class="amado-btn-group mt-30 mb-100">
                    <a href="#" class="search-nav btn amado-btn mb-15">Search</a>
                </div>
                <!-- Cart Menu -->
                <div class="cart-fav-search mb-100">
                    <a asp-controller="Cart" asp-action="ViewCart"><i class="fas fa-shopping-cart" style="color: rgb(193, 188, 188);margin-right:12px;margin-left:4px;"></i> Cart
                        @await Component.InvokeAsync("Cart")</span></a>
                    <a asp-controller="Checkout" asp-action="MainOrderDetails"><i class="fas fa-money" style="color: rgb(193, 188, 188);margin-right:12px;margin-left:4px;"></i> Order</span></a>
                    <a asp-controller="Checkout" asp-action="Checkout"><i class="fas fa-credit-card-alt" style="color: rgb(193, 188, 188);margin-right:12px;margin-left:4px;"></i> Checkout</span></a>

                    <a asp-controller="Feedback" asp-action="Index">
                        <i class="fas fa-envelope" style="color: rgb(193, 188, 188);margin-right:12px;margin-left:4px;"></i>
                            Feedback
                    </a>
                </div>

            @if (User.Identity.IsAuthenticated && User.Identity.Name.ToLower() == "admin@123.com")
            {
                <div class="amado-btn-group mt-30 mb-100">
                    <p> Admin </p>
                    <nav class="amado-nav">
                        <ul>
                            <li class="@(page == "AddProduct" ? "active" : "")"><a asp-controller="Product"
                                    asp-action="AddProduct">Add Product</a></li>
                            <li class="@(page == "ProductsManage" ? "active" : "")"><a asp-controller="Product"
                                    asp-action="ProductsManage">Products Manage</a></li>
                        </ul>
                    </nav>
                </div>
            }
                

                <!-- Social Button -->
                <div class="social-info d-flex justify-content-between">
                    <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </div>
            </header>
            <!-- Header Area End -->

            <!-- Product Catagories Area Start -->
            <div class="products-catagories-area clearfix">
                @RenderBody()
            </div>
            <!-- Product Catagories Area End -->
        </div>
    </div>


    <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate
                            consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>

                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="~/img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->&
                            Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
                        </p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#footerNavContent" aria-controls="footerNavContent"
                                    aria-expanded="false" aria-label="Toggle navigation"><i
                                        class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Product" asp-action="Products">Shop</a>
                                        </li>
                                        <partial name="_LoginPartial" />
                                    </ul>
                                </div>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>